name: Build and deploy APT repository to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read        # to pull code
  pages: write          # to publish to Pages
  id-token: write       # for OIDC if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true               # pull Git LFS files if you use them

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload site contents as Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            pool/
            dists/
            images/
            README.md
            minios-linux.asc

  publish:
    needs: deploy
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
