name: Deploy static APT repo to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: 'read'
  pages: 'write'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Pull Git LFS objects
        run: git lfs pull

      - name: Upload site contents for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: |
            pool/
            dists/

  publish:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
